version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}